[build]
  command = "npm run build"
  publish = "dist"         # or "build" etc.
  functions = "netlify/functions"

[dev]
  command    = "npm run dev"   # Vite dev
  targetPort = 5173            # Vite's port (change if different)
  port       = 8888            # Netlify proxy port
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
